name: "user"
mode: "dev"
version: "1.0.1"
port: 10002
start_time: "2020-07-01"
machine_id: 2

log:
  level: "debug"
  filename: "logs/user.log"
  max_size: 20
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "yhy3426356"
  dbname: "sso"
  max_open_connection: 1000
  max_idle_connection: 100

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 1

jwt:
  key: ""
  expire_time: "6000"
  issuer: "ipfsmain"